### ISSUE TITLE
Unable to use the tool

### ISSUE THREAD

**Issue by adhisadi** [10XGenomics/vartrix#62] opened 2021-06-21 11:42 UTC
I am unable to use the tool. I installed vartrix with the source code. I also installed Rust from within the directory containing the VarTrix source code. I have these inside my directory : Cargo.lock  Cargo.toml  LICENSE  README.md  VarTrix_WorkFlow.png  ci  construct_linux_binary.py  src  target  test

These are my issues:
I get this error with cargo build --release
`[ERROR] The resulting matrix has a sum of 0. Did you use the --umi flag on data without UMIs?`

I do not see vartrix inside "target/release/"

And I  get vartrix: command not found. 
Could you help me installation or usage issue I am dealing with?

**Comment by XUEbaogai0101** [comment] 2022-05-28 23:03
Hi @adhisadi,  I am encountering the same "issue".
Were you able to solve this?

Here I share the command line I am using and the results:
```
cargo test --release

Compiling vartrix v1.1.22 (/data/user/*/vartrix-1.1.22)
Finished release [optimized + debuginfo] target(s) in 24.28s
Running unittests src/main.rs (target/release/deps/vartrix-c59c3ec5b2fc0f12)
running 7 tests
test tests::test_frac_matrix ... ok
test tests::test_coverage_matrices_umi ... ok
test tests::test_consensus_matrix ... ok
test tests::test_coverage_matrices_umi_gzipped_bcs ... ok
test tests::test_coverage_matrices ... ok
22:48:17 [ERROR] The resulting matrix has a sum of 0. Did you use the --umi flag on data without UMIs?
test tests::test_coverage_matrices_umi_dna ... ok
test tests::test_coverage_matrices_dna ... ok
test result: ok. 7 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.96s
```

Best,
XUE

**Comment by pmarks** [comment] 2022-05-31 19:36
@XUEbaogai0101 You need to run `cargo build --release` - that will create the vartrix program at `target/release/vartrix`.   Here you've run `cargo test --release` which just runs the built-in unit tests.  @adhisadi is that potentially the same problem you were seeing?  I'll close this issue - please re-open if you're still having problems.

**Closed by pmarks** 2022-05-31 19:36 UTC

**Comment by ErminZ** [comment] 2024-08-14 15:32
Update, the  [ERROR] The resulting matrix has a sum of 0. Did you use the --umi flag on data without UMIs in my case is caused by the barcodes (TTGGAACAGTACGACG-1)  are not matched in the BAM file (TTGGAACAGTACGACG). 

VarTrix installation: 
`wget https://github.com/10XGenomics/vartrix/releases/download/v1.1.22/vartrix_linux`

```
mv vartrix_linux vartrix
chmod +x vartrix
./vartrix --help
```
To run vartrix, no matter use `--umi` or not, using different bam input, always get the same error: The resulting matrix has a sum of 0. Did you use the --umi flag on data without UMIs
```
./vartrix -v ../clair3/merge_output.vcf -b ../.tagged.bam \
-f GCA_set.fna \
-c barcodes.tsv.gz \
--out-matrix ../vartrix/out_matrix.mtx \
--umi --threads 4
```
